### PR TITLE
upgrade to .net 5.0

### PR DESCRIPTION
**Pull request by maikebing**

### CODE REVIEW

**Comment by maikebing** [comment]
image

**Review by StefH — CHANGES_REQUESTED** [review]
If I see correctly, the old .NET 4.0 target is gone?

**Comment by maikebing** [comment]
<ItemGroup  Condition=" '$(TargetFramework)' == 'net40' ">
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>

**Comment by maikebing** [comment]
`  <TargetFrameworks>net40;net5.0-windows</TargetFrameworks>`

**Comment by StefH** [comment]
Hello @maikebing,

When running your master branch on my system, the example project works, However the syntax highlighting is missing/broken?
image

**Comment by maikebing** [comment]
I've been trying to fix it, but I haven't been able to fix it.

**Comment by StefH** [comment]
@maikebing 
This is because the resources are not defined as embedded resource:
Can you please add this to the csproj:
``` xml
  <ItemGroup>
    <EmbeddedResource Include="Resources\*.*" />
  </ItemGroup>
```

**Comment by maikebing** [comment]
LGTM

**Pull request merged**
